// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.Collections.Runtime")>]
[<assembly: AssemblyProductAttribute("Sylvester.Provider.Collections")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Sylvester.Provider.Collections.")>]
[<assembly: AssemblyVersionAttribute("0.2.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.Collections.Runtime"
    let [<Literal>] AssemblyProduct = "Sylvester.Provider.Collections"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Sylvester.Provider.Collections."
    let [<Literal>] AssemblyVersion = "0.2.0"
    let [<Literal>] AssemblyFileVersion = "0.2.0"
