// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.tf.Graphs.Runtime")>]
[<assembly: AssemblyProductAttribute("Sylvester.Provider.tf.Graphs")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Sylvester.Provider.tf.Graphs.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.tf.Graphs.Runtime"
    let [<Literal>] AssemblyProduct = "Sylvester.Provider.tf.Graphs"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Sylvester.Provider.tf.Graphs."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
