node {
name: "m_0"
op: "Placeholder"
attr {
"shape": shape {
dim {
size: "6"
}
dim {
size: "100"
}

}
"dtype": type: "DT_FLOAT"
}
}
node {
name: "m_1"
op: "Placeholder"
attr {
"shape": shape {
dim {
size: "6"
}
dim {
size: "100"
}

}
"dtype": type: "DT_FLOAT"
}
}
node {
name: "m_2"
op: "Placeholder"
attr {
"shape": shape {
dim {
size: "100"
}
dim {
size: "200"
}

}
"dtype": type: "DT_FLOAT"
}
}
node {
name: "MatOps/Add_0"
op: "Add"
input: "m_0"
input: "m_1"

attr {
"T": type: "DT_FLOAT"
}
}
node {
name: "MatOps/MatMul_0"
op: "MatMul"
input: "MatOps/Add_0"
input: "m_2"

attr {
"transpose_b": b: false
"T": type: "DT_FLOAT"
"transpose_a": b: false
}
}
library {

}
versions {
producer: 119
}