@echo off
.paket\paket update
echo Building x64 debug configuration...
dotnet build -c debug /p:Platform=x64
echo Building AnyCPU debug configuration...
dotnet build -c debug

echo Building x64 release configuration...
dotnet build -c release /p:Platform=x64
echo Building AnyCPU release configuration...
dotnet build -c release