//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from antlr-grammars\tptp_v7_0_0_0.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="tptp_v7_0_0_0Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface Itptp_v7_0_0_0Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tptp_file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTptp_file([NotNull] tptp_v7_0_0_0Parser.Tptp_fileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tptp_input"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTptp_input([NotNull] tptp_v7_0_0_0Parser.Tptp_inputContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.annotated_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotated_formula([NotNull] tptp_v7_0_0_0Parser.Annotated_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tpi_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTpi_annotated([NotNull] tptp_v7_0_0_0Parser.Tpi_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tpi_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTpi_formula([NotNull] tptp_v7_0_0_0Parser.Tpi_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_annotated([NotNull] tptp_v7_0_0_0Parser.Thf_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tfx_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTfx_annotated([NotNull] tptp_v7_0_0_0Parser.Tfx_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_annotated([NotNull] tptp_v7_0_0_0Parser.Tff_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tcf_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcf_annotated([NotNull] tptp_v7_0_0_0Parser.Tcf_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_annotated([NotNull] tptp_v7_0_0_0Parser.Fof_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.cnf_annotated"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCnf_annotated([NotNull] tptp_v7_0_0_0Parser.Cnf_annotatedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.annotations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotations([NotNull] tptp_v7_0_0_0Parser.AnnotationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.formula_role"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_role([NotNull] tptp_v7_0_0_0Parser.Formula_roleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_formula([NotNull] tptp_v7_0_0_0Parser.Thf_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_logic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_logic_formula([NotNull] tptp_v7_0_0_0Parser.Thf_logic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_binary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_binary_formula([NotNull] tptp_v7_0_0_0Parser.Thf_binary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_binary_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_binary_pair([NotNull] tptp_v7_0_0_0Parser.Thf_binary_pairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_binary_tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_binary_tuple([NotNull] tptp_v7_0_0_0Parser.Thf_binary_tupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_or_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_or_formula([NotNull] tptp_v7_0_0_0Parser.Thf_or_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_and_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_and_formula([NotNull] tptp_v7_0_0_0Parser.Thf_and_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_apply_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_apply_formula([NotNull] tptp_v7_0_0_0Parser.Thf_apply_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_unitary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_unitary_formula([NotNull] tptp_v7_0_0_0Parser.Thf_unitary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_quantified_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_quantified_formula([NotNull] tptp_v7_0_0_0Parser.Thf_quantified_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_quantification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_quantification([NotNull] tptp_v7_0_0_0Parser.Thf_quantificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_variable([NotNull] tptp_v7_0_0_0Parser.Thf_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_typed_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_typed_variable([NotNull] tptp_v7_0_0_0Parser.Thf_typed_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_unary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_unary_formula([NotNull] tptp_v7_0_0_0Parser.Thf_unary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_atom([NotNull] tptp_v7_0_0_0Parser.Thf_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_function([NotNull] tptp_v7_0_0_0Parser.Thf_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_conn_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_conn_term([NotNull] tptp_v7_0_0_0Parser.Thf_conn_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_conditional([NotNull] tptp_v7_0_0_0Parser.Thf_conditionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_let([NotNull] tptp_v7_0_0_0Parser.Thf_letContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_arguments([NotNull] tptp_v7_0_0_0Parser.Thf_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_type_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_type_formula([NotNull] tptp_v7_0_0_0Parser.Thf_type_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_typeable_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_typeable_formula([NotNull] tptp_v7_0_0_0Parser.Thf_typeable_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_subtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_subtype([NotNull] tptp_v7_0_0_0Parser.Thf_subtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_top_level_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_top_level_type([NotNull] tptp_v7_0_0_0Parser.Thf_top_level_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_unitary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_unitary_type([NotNull] tptp_v7_0_0_0Parser.Thf_unitary_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_apply_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_apply_type([NotNull] tptp_v7_0_0_0Parser.Thf_apply_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_binary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_binary_type([NotNull] tptp_v7_0_0_0Parser.Thf_binary_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_mapping_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_mapping_type([NotNull] tptp_v7_0_0_0Parser.Thf_mapping_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_xprod_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_xprod_type([NotNull] tptp_v7_0_0_0Parser.Thf_xprod_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_union_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_union_type([NotNull] tptp_v7_0_0_0Parser.Thf_union_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_sequent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_sequent([NotNull] tptp_v7_0_0_0Parser.Thf_sequentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_tuple([NotNull] tptp_v7_0_0_0Parser.Thf_tupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_formula_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_formula_list([NotNull] tptp_v7_0_0_0Parser.Thf_formula_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tfx_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTfx_formula([NotNull] tptp_v7_0_0_0Parser.Tfx_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tfx_logic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTfx_logic_formula([NotNull] tptp_v7_0_0_0Parser.Tfx_logic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_formula([NotNull] tptp_v7_0_0_0Parser.Tff_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_logic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_logic_formula([NotNull] tptp_v7_0_0_0Parser.Tff_logic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_binary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_binary_formula([NotNull] tptp_v7_0_0_0Parser.Tff_binary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_binary_nonassoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_binary_nonassoc([NotNull] tptp_v7_0_0_0Parser.Tff_binary_nonassocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_binary_assoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_binary_assoc([NotNull] tptp_v7_0_0_0Parser.Tff_binary_assocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_or_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_or_formula([NotNull] tptp_v7_0_0_0Parser.Tff_or_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_and_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_and_formula([NotNull] tptp_v7_0_0_0Parser.Tff_and_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_unitary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_unitary_formula([NotNull] tptp_v7_0_0_0Parser.Tff_unitary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_quantified_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_quantified_formula([NotNull] tptp_v7_0_0_0Parser.Tff_quantified_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_variable_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_variable_list([NotNull] tptp_v7_0_0_0Parser.Tff_variable_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_variable([NotNull] tptp_v7_0_0_0Parser.Tff_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_typed_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_typed_variable([NotNull] tptp_v7_0_0_0Parser.Tff_typed_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_unary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_unary_formula([NotNull] tptp_v7_0_0_0Parser.Tff_unary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_atomic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_atomic_formula([NotNull] tptp_v7_0_0_0Parser.Tff_atomic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_conditional([NotNull] tptp_v7_0_0_0Parser.Tff_conditionalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let([NotNull] tptp_v7_0_0_0Parser.Tff_letContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_term_defns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_term_defns([NotNull] tptp_v7_0_0_0Parser.Tff_let_term_defnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_term_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_term_list([NotNull] tptp_v7_0_0_0Parser.Tff_let_term_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_term_defn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_term_defn([NotNull] tptp_v7_0_0_0Parser.Tff_let_term_defnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_term_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_term_binding([NotNull] tptp_v7_0_0_0Parser.Tff_let_term_bindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_formula_defns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_formula_defns([NotNull] tptp_v7_0_0_0Parser.Tff_let_formula_defnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_formula_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_formula_list([NotNull] tptp_v7_0_0_0Parser.Tff_let_formula_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_formula_defn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_formula_defn([NotNull] tptp_v7_0_0_0Parser.Tff_let_formula_defnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_formula_binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_formula_binding([NotNull] tptp_v7_0_0_0Parser.Tff_let_formula_bindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_sequent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_sequent([NotNull] tptp_v7_0_0_0Parser.Tff_sequentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_formula_tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_formula_tuple([NotNull] tptp_v7_0_0_0Parser.Tff_formula_tupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_formula_tuple_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_formula_tuple_list([NotNull] tptp_v7_0_0_0Parser.Tff_formula_tuple_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_typed_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_typed_atom([NotNull] tptp_v7_0_0_0Parser.Tff_typed_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_subtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_subtype([NotNull] tptp_v7_0_0_0Parser.Tff_subtypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_top_level_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_top_level_type([NotNull] tptp_v7_0_0_0Parser.Tff_top_level_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tf1_quantified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTf1_quantified_type([NotNull] tptp_v7_0_0_0Parser.Tf1_quantified_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_monotype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_monotype([NotNull] tptp_v7_0_0_0Parser.Tff_monotypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_unitary_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_unitary_type([NotNull] tptp_v7_0_0_0Parser.Tff_unitary_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_atomic_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_atomic_type([NotNull] tptp_v7_0_0_0Parser.Tff_atomic_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_type_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_type_arguments([NotNull] tptp_v7_0_0_0Parser.Tff_type_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_mapping_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_mapping_type([NotNull] tptp_v7_0_0_0Parser.Tff_mapping_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_xprod_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_xprod_type([NotNull] tptp_v7_0_0_0Parser.Tff_xprod_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tcf_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcf_formula([NotNull] tptp_v7_0_0_0Parser.Tcf_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tcf_logic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcf_logic_formula([NotNull] tptp_v7_0_0_0Parser.Tcf_logic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tcf_quantified_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTcf_quantified_formula([NotNull] tptp_v7_0_0_0Parser.Tcf_quantified_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_formula([NotNull] tptp_v7_0_0_0Parser.Fof_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_logic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_logic_formula([NotNull] tptp_v7_0_0_0Parser.Fof_logic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_binary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_binary_formula([NotNull] tptp_v7_0_0_0Parser.Fof_binary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_binary_nonassoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_binary_nonassoc([NotNull] tptp_v7_0_0_0Parser.Fof_binary_nonassocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_binary_assoc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_binary_assoc([NotNull] tptp_v7_0_0_0Parser.Fof_binary_assocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_or_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_or_formula([NotNull] tptp_v7_0_0_0Parser.Fof_or_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_and_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_and_formula([NotNull] tptp_v7_0_0_0Parser.Fof_and_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_unitary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_unitary_formula([NotNull] tptp_v7_0_0_0Parser.Fof_unitary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_quantified_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_quantified_formula([NotNull] tptp_v7_0_0_0Parser.Fof_quantified_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_variable_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_variable_list([NotNull] tptp_v7_0_0_0Parser.Fof_variable_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_unary_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_unary_formula([NotNull] tptp_v7_0_0_0Parser.Fof_unary_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_infix_unary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_infix_unary([NotNull] tptp_v7_0_0_0Parser.Fof_infix_unaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_atomic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_atomic_formula([NotNull] tptp_v7_0_0_0Parser.Fof_atomic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_plain_atomic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_plain_atomic_formula([NotNull] tptp_v7_0_0_0Parser.Fof_plain_atomic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_atomic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_atomic_formula([NotNull] tptp_v7_0_0_0Parser.Fof_defined_atomic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_plain_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_plain_formula([NotNull] tptp_v7_0_0_0Parser.Fof_defined_plain_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_infix_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_infix_formula([NotNull] tptp_v7_0_0_0Parser.Fof_defined_infix_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_system_atomic_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_system_atomic_formula([NotNull] tptp_v7_0_0_0Parser.Fof_system_atomic_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_plain_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_plain_term([NotNull] tptp_v7_0_0_0Parser.Fof_plain_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_term([NotNull] tptp_v7_0_0_0Parser.Fof_defined_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_atomic_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_atomic_term([NotNull] tptp_v7_0_0_0Parser.Fof_defined_atomic_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_defined_plain_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_defined_plain_term([NotNull] tptp_v7_0_0_0Parser.Fof_defined_plain_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_system_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_system_term([NotNull] tptp_v7_0_0_0Parser.Fof_system_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_arguments([NotNull] tptp_v7_0_0_0Parser.Fof_argumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_term([NotNull] tptp_v7_0_0_0Parser.Fof_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_function_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_function_term([NotNull] tptp_v7_0_0_0Parser.Fof_function_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_conditional_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_conditional_term([NotNull] tptp_v7_0_0_0Parser.Tff_conditional_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_let_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_let_term([NotNull] tptp_v7_0_0_0Parser.Tff_let_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_tuple_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_tuple_term([NotNull] tptp_v7_0_0_0Parser.Tff_tuple_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_sequent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_sequent([NotNull] tptp_v7_0_0_0Parser.Fof_sequentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_formula_tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_formula_tuple([NotNull] tptp_v7_0_0_0Parser.Fof_formula_tupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_formula_tuple_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_formula_tuple_list([NotNull] tptp_v7_0_0_0Parser.Fof_formula_tuple_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.cnf_formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCnf_formula([NotNull] tptp_v7_0_0_0Parser.Cnf_formulaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.cnf_disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCnf_disjunction([NotNull] tptp_v7_0_0_0Parser.Cnf_disjunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.cnf_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCnf_literal([NotNull] tptp_v7_0_0_0Parser.Cnf_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_quantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_quantifier([NotNull] tptp_v7_0_0_0Parser.Thf_quantifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.th0_quantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTh0_quantifier([NotNull] tptp_v7_0_0_0Parser.Th0_quantifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.th1_quantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTh1_quantifier([NotNull] tptp_v7_0_0_0Parser.Th1_quantifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_pair_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_pair_connective([NotNull] tptp_v7_0_0_0Parser.Thf_pair_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.thf_unary_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThf_unary_connective([NotNull] tptp_v7_0_0_0Parser.Thf_unary_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.th1_unary_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTh1_unary_connective([NotNull] tptp_v7_0_0_0Parser.Th1_unary_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.tff_pair_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTff_pair_connective([NotNull] tptp_v7_0_0_0Parser.Tff_pair_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.fof_quantifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFof_quantifier([NotNull] tptp_v7_0_0_0Parser.Fof_quantifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.binary_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_connective([NotNull] tptp_v7_0_0_0Parser.Binary_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.assoc_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssoc_connective([NotNull] tptp_v7_0_0_0Parser.Assoc_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.unary_connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_connective([NotNull] tptp_v7_0_0_0Parser.Unary_connectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.type_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_constant([NotNull] tptp_v7_0_0_0Parser.Type_constantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.type_functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_functor([NotNull] tptp_v7_0_0_0Parser.Type_functorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_type([NotNull] tptp_v7_0_0_0Parser.Defined_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.system_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystem_type([NotNull] tptp_v7_0_0_0Parser.System_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] tptp_v7_0_0_0Parser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.untyped_atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUntyped_atom([NotNull] tptp_v7_0_0_0Parser.Untyped_atomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_proposition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_proposition([NotNull] tptp_v7_0_0_0Parser.Defined_propositionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_predicate([NotNull] tptp_v7_0_0_0Parser.Defined_predicateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_infix_pred"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_infix_pred([NotNull] tptp_v7_0_0_0Parser.Defined_infix_predContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] tptp_v7_0_0_0Parser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctor([NotNull] tptp_v7_0_0_0Parser.FunctorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.system_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystem_constant([NotNull] tptp_v7_0_0_0Parser.System_constantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.system_functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystem_functor([NotNull] tptp_v7_0_0_0Parser.System_functorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_constant([NotNull] tptp_v7_0_0_0Parser.Defined_constantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_functor([NotNull] tptp_v7_0_0_0Parser.Defined_functorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.defined_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefined_term([NotNull] tptp_v7_0_0_0Parser.Defined_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] tptp_v7_0_0_0Parser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSource([NotNull] tptp_v7_0_0_0Parser.SourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.sources"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSources([NotNull] tptp_v7_0_0_0Parser.SourcesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.dag_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDag_source([NotNull] tptp_v7_0_0_0Parser.Dag_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_record([NotNull] tptp_v7_0_0_0Parser.Inference_recordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_rule([NotNull] tptp_v7_0_0_0Parser.Inference_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_parents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_parents([NotNull] tptp_v7_0_0_0Parser.Inference_parentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.parent_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParent_list([NotNull] tptp_v7_0_0_0Parser.Parent_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.parent_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParent_info([NotNull] tptp_v7_0_0_0Parser.Parent_infoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.parent_details"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParent_details([NotNull] tptp_v7_0_0_0Parser.Parent_detailsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.internal_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInternal_source([NotNull] tptp_v7_0_0_0Parser.Internal_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.intro_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntro_type([NotNull] tptp_v7_0_0_0Parser.Intro_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.external_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_source([NotNull] tptp_v7_0_0_0Parser.External_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.file_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_source([NotNull] tptp_v7_0_0_0Parser.File_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.file_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_info([NotNull] tptp_v7_0_0_0Parser.File_infoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.theory"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheory([NotNull] tptp_v7_0_0_0Parser.TheoryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.theory_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheory_name([NotNull] tptp_v7_0_0_0Parser.Theory_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.creator_source"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreator_source([NotNull] tptp_v7_0_0_0Parser.Creator_sourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.creator_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreator_name([NotNull] tptp_v7_0_0_0Parser.Creator_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.optional_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptional_info([NotNull] tptp_v7_0_0_0Parser.Optional_infoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.useful_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUseful_info([NotNull] tptp_v7_0_0_0Parser.Useful_infoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.info_items"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfo_items([NotNull] tptp_v7_0_0_0Parser.Info_itemsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.info_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInfo_item([NotNull] tptp_v7_0_0_0Parser.Info_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.formula_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_item([NotNull] tptp_v7_0_0_0Parser.Formula_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.description_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription_item([NotNull] tptp_v7_0_0_0Parser.Description_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.iquote_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIquote_item([NotNull] tptp_v7_0_0_0Parser.Iquote_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_item([NotNull] tptp_v7_0_0_0Parser.Inference_itemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_status"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_status([NotNull] tptp_v7_0_0_0Parser.Inference_statusContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.status_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatus_value([NotNull] tptp_v7_0_0_0Parser.Status_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.inference_info"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInference_info([NotNull] tptp_v7_0_0_0Parser.Inference_infoContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.assumptions_record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssumptions_record([NotNull] tptp_v7_0_0_0Parser.Assumptions_recordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.refutation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefutation([NotNull] tptp_v7_0_0_0Parser.RefutationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.new_symbol_record"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_symbol_record([NotNull] tptp_v7_0_0_0Parser.New_symbol_recordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.new_symbol_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNew_symbol_list([NotNull] tptp_v7_0_0_0Parser.New_symbol_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.principal_symbol"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrincipal_symbol([NotNull] tptp_v7_0_0_0Parser.Principal_symbolContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclude([NotNull] tptp_v7_0_0_0Parser.IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.formula_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_selection([NotNull] tptp_v7_0_0_0Parser.Formula_selectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_list([NotNull] tptp_v7_0_0_0Parser.Name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.general_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_term([NotNull] tptp_v7_0_0_0Parser.General_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.general_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_data([NotNull] tptp_v7_0_0_0Parser.General_dataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.general_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_function([NotNull] tptp_v7_0_0_0Parser.General_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.formula_data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFormula_data([NotNull] tptp_v7_0_0_0Parser.Formula_dataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.general_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_list([NotNull] tptp_v7_0_0_0Parser.General_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.general_terms"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_terms([NotNull] tptp_v7_0_0_0Parser.General_termsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] tptp_v7_0_0_0Parser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.atomic_word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomic_word([NotNull] tptp_v7_0_0_0Parser.Atomic_wordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.atomic_defined_word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomic_defined_word([NotNull] tptp_v7_0_0_0Parser.Atomic_defined_wordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.atomic_system_word"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtomic_system_word([NotNull] tptp_v7_0_0_0Parser.Atomic_system_wordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] tptp_v7_0_0_0Parser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="tptp_v7_0_0_0Parser.file_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile_name([NotNull] tptp_v7_0_0_0Parser.File_nameContext context);
}
