// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.ND.Runtime")>]
[<assembly: AssemblyProductAttribute("Sylvester.Provider.ND")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Sylvester.Provider.ND.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.ND.Runtime"
    let [<Literal>] AssemblyProduct = "Sylvester.Provider.ND"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Sylvester.Provider.ND."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
