// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.Arithmetic.DesignTime")>]
[<assembly: AssemblyProductAttribute("Sylvester")>]
[<assembly: AssemblyDescriptionAttribute("Design-time assembly for the Sylvester.Arithmetic type provider.")>]
[<assembly: AssemblyVersionAttribute("0.2.8.0")>]
[<assembly: AssemblyFileVersionAttribute("0.2.8.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.Arithmetic.DesignTime"
    let [<Literal>] AssemblyProduct = "Sylvester"
    let [<Literal>] AssemblyDescription = "Design-time assembly for the Sylvester.Arithmetic type provider."
    let [<Literal>] AssemblyVersion = "0.2.8.0"
    let [<Literal>] AssemblyFileVersion = "0.2.8.0"
