#r ".\\..\\..\\src\\Providers\\Sylvester.Provider.Arithmetic\\src\\Sylvester.Provider.Arithmetic.Runtime\\bin\\Release\\net45\\Sylvester.Provider.Arithmetic.Runtime.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.Api.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.Api.Fs.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.Collections.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.Tensors.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.Graphs.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.tf.Api.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Sylvester.tf.dll"

#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Google.ProtoBuf.dll"
#r ".\\..\\..\\src\\Fabrics\\tf\\Sylvester.tf\\bin\\x64\\Debug\\net45\\Protobuf.Text.dll"