// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.Collections.DesignTime")>]
[<assembly: AssemblyProductAttribute("Sylvester.Provider.Collections")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Sylvester.Provider.Collections.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.Collections.DesignTime"
    let [<Literal>] AssemblyProduct = "Sylvester.Provider.Collections"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Sylvester.Provider.Collections."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
