// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Sylvester.Provider.Arithmetic.Runtime")>]
[<assembly: AssemblyProductAttribute("Sylvester")>]
[<assembly: AssemblyDescriptionAttribute("Run-time assembly for the Sylvester.Arithmetic type provider.")>]
[<assembly: AssemblyVersionAttribute("0.2.5.1")>]
[<assembly: AssemblyFileVersionAttribute("0.2.5.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Sylvester.Provider.Arithmetic.Runtime"
    let [<Literal>] AssemblyProduct = "Sylvester"
    let [<Literal>] AssemblyDescription = "Run-time assembly for the Sylvester.Arithmetic type provider."
    let [<Literal>] AssemblyVersion = "0.2.5.1"
    let [<Literal>] AssemblyFileVersion = "0.2.5.1"
